#!/bin/bash

mkdir data

wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1gdRuogqmlOISPXt_RfK2O3xatdP47zeJ' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1gdRuogqmlOISPXt_RfK2O3xatdP47zeJ" -O data/20200423-1804_states_timestep_mod_25.pickle && rm -rf /tmp/cookies.txt

exec "$@"
